[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aria_pylib"
version = "0.1.0"
description = "A Python library for working with Project Aria VRS recordings, providing tools for data access, processing, and analysis."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name="Gianluca Malvisi", email="g.malvisi04@gmail.com" },
]
license = { text = "MIT" }
keywords = ["projectaria", "vrs", "multistream", "computer-vision"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

# Core dependencies for the library
dependencies = [
    "projectaria-tools",
    "numpy",
    "torch",
    "opencv-python",
    "tqdm",
    "matplotlib",
    "pandas",
]

[project.urls]
"Homepage" = "https://github.com/gianMalvisi/ariagen1"

[tool.hatch.build.targets.wheel]
packages = ["aria_pylib"]